package com.example.lawyerapp;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.lawyerapp.CaseContacts;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CASE_CONTACTS.
*/
public class CaseContactsDao extends AbstractDao<CaseContacts, Long> {

    public static final String TABLENAME = "CASE_CONTACTS";

    /**
     * Properties of entity CaseContacts.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CaseID = new Property(1, Long.class, "caseID", false, "CASE_ID");
        public final static Property ContactID = new Property(2, Long.class, "contactID", false, "CONTACT_ID");
    };


    public CaseContactsDao(DaoConfig config) {
        super(config);
    }
    
    public CaseContactsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CASE_CONTACTS' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'CASE_ID' INTEGER," + // 1: caseID
                "'CONTACT_ID' INTEGER);"); // 2: contactID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CASE_CONTACTS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CaseContacts entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long caseID = entity.getCaseID();
        if (caseID != null) {
            stmt.bindLong(2, caseID);
        }
 
        Long contactID = entity.getContactID();
        if (contactID != null) {
            stmt.bindLong(3, contactID);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CaseContacts readEntity(Cursor cursor, int offset) {
        CaseContacts entity = new CaseContacts( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // caseID
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // contactID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CaseContacts entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCaseID(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setContactID(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(CaseContacts entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(CaseContacts entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
