package com.example.lawyerapp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CASES.
 */
public class Cases {

    private Long id;
    private String name;
    private String casetype;
    private String caseDate;
    private java.util.Date date;

    public Cases() {
    }

    public Cases(Long id) {
        this.id = id;
    }

    public Cases(Long id, String name, String casetype, String caseDate, java.util.Date date) {
        this.id = id;
        this.name = name;
        this.casetype = casetype;
        this.caseDate = caseDate;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCasetype() {
        return casetype;
    }

    public void setCasetype(String casetype) {
        this.casetype = casetype;
    }

    public String getCaseDate() {
        return caseDate;
    }

    public void setCaseDate(String caseDate) {
        this.caseDate = caseDate;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
