package com.example.lawyerapp;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.lawyerapp.Logs;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table LOGS.
*/
public class LogsDao extends AbstractDao<Logs, Long> {

    public static final String TABLENAME = "LOGS";

    /**
     * Properties of entity Logs.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property ParentID = new Property(2, Long.class, "parentID", false, "PARENT_ID");
        public final static Property LogDate = new Property(3, String.class, "logDate", false, "LOG_DATE");
        public final static Property Date = new Property(4, java.util.Date.class, "date", false, "DATE");
        public final static Property Notes = new Property(5, String.class, "notes", false, "NOTES");
        public final static Property LogType = new Property(6, String.class, "logType", false, "LOG_TYPE");
        public final static Property Hours = new Property(7, Float.class, "hours", false, "HOURS");
        public final static Property Mileage = new Property(8, Float.class, "mileage", false, "MILEAGE");
        public final static Property Expenses = new Property(9, Float.class, "expenses", false, "EXPENSES");
    };


    public LogsDao(DaoConfig config) {
        super(config);
    }
    
    public LogsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'LOGS' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NAME' TEXT," + // 1: name
                "'PARENT_ID' INTEGER," + // 2: parentID
                "'LOG_DATE' TEXT," + // 3: logDate
                "'DATE' INTEGER," + // 4: date
                "'NOTES' TEXT," + // 5: notes
                "'LOG_TYPE' TEXT," + // 6: logType
                "'HOURS' REAL," + // 7: hours
                "'MILEAGE' REAL," + // 8: mileage
                "'EXPENSES' REAL);"); // 9: expenses
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'LOGS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Logs entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        Long parentID = entity.getParentID();
        if (parentID != null) {
            stmt.bindLong(3, parentID);
        }
 
        String logDate = entity.getLogDate();
        if (logDate != null) {
            stmt.bindString(4, logDate);
        }
 
        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(5, date.getTime());
        }
 
        String notes = entity.getNotes();
        if (notes != null) {
            stmt.bindString(6, notes);
        }
 
        String logType = entity.getLogType();
        if (logType != null) {
            stmt.bindString(7, logType);
        }
 
        Float hours = entity.getHours();
        if (hours != null) {
            stmt.bindDouble(8, hours);
        }
 
        Float mileage = entity.getMileage();
        if (mileage != null) {
            stmt.bindDouble(9, mileage);
        }
 
        Float expenses = entity.getExpenses();
        if (expenses != null) {
            stmt.bindDouble(10, expenses);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Logs readEntity(Cursor cursor, int offset) {
        Logs entity = new Logs( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // parentID
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // logDate
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)), // date
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // notes
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // logType
            cursor.isNull(offset + 7) ? null : cursor.getFloat(offset + 7), // hours
            cursor.isNull(offset + 8) ? null : cursor.getFloat(offset + 8), // mileage
            cursor.isNull(offset + 9) ? null : cursor.getFloat(offset + 9) // expenses
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Logs entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setParentID(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setLogDate(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDate(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setNotes(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setLogType(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setHours(cursor.isNull(offset + 7) ? null : cursor.getFloat(offset + 7));
        entity.setMileage(cursor.isNull(offset + 8) ? null : cursor.getFloat(offset + 8));
        entity.setExpenses(cursor.isNull(offset + 9) ? null : cursor.getFloat(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Logs entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Logs entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
