package com.example.lawyerapp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOGS.
 */
public class Logs {

    private Long id;
    private String name;
    private Long parentID;
    private String logDate;
    private java.util.Date date;
    private String notes;
    private String logType;
    private Float hours;
    private Float mileage;
    private Float expenses;

    public Logs() {
    }

    public Logs(Long id) {
        this.id = id;
    }

    public Logs(Long id, String name, Long parentID, String logDate, java.util.Date date, String notes, String logType, Float hours, Float mileage, Float expenses) {
        this.id = id;
        this.name = name;
        this.parentID = parentID;
        this.logDate = logDate;
        this.date = date;
        this.notes = notes;
        this.logType = logType;
        this.hours = hours;
        this.mileage = mileage;
        this.expenses = expenses;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getParentID() {
        return parentID;
    }

    public void setParentID(Long parentID) {
        this.parentID = parentID;
    }

    public String getLogDate() {
        return logDate;
    }

    public void setLogDate(String logDate) {
        this.logDate = logDate;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public String getLogType() {
        return logType;
    }

    public void setLogType(String logType) {
        this.logType = logType;
    }

    public Float getHours() {
        return hours;
    }

    public void setHours(Float hours) {
        this.hours = hours;
    }

    public Float getMileage() {
        return mileage;
    }

    public void setMileage(Float mileage) {
        this.mileage = mileage;
    }

    public Float getExpenses() {
        return expenses;
    }

    public void setExpenses(Float expenses) {
        this.expenses = expenses;
    }

}
